# action.yml
name: 'Simple API'
description: 'Simple API to make a post request'
inputs:
  post-body:  # id of input
    description: 'json'
    required: true
    default: '{\"name\":\"test\"}'
outputs:
  post-result: # id of output
    description: 'result of the post request'
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v2
    - run: |
        POST_BODY='${{inputs.post-body}}' docker-compose up  --abort-on-container-exit
        output=$(docker-compose logs --no-color | tail -1)
        echo $output | sed 's/.*?{//'
      shell: bash
