version: "3.9"
services:
  api:
    build: .
    image: simple-api:latest
    ports:
      - "3000:3000"

  sh:
    image: ubuntu:latest
    command: '/bin/sh -c "echo $$POST_BODY"'


  curl: 
    image: curlimages/curl
    depends_on:
      - api
    command: >-
      curl
      -X POST
      -d "$POST_BODY"
      -H "Content-Type: application/json"
      http://api:3000/handle
