version: "3.9"
services:
  api:
    build: .
    image: simple-api:latest
    ports:
      - "3000:3000"

  #sh:
  #  entrypoint: /bin/sh
  #  command: -c "echo '${POST_BODY}'"
  #  image: ubuntu
  #  tty: true

  #curl: 
  #  image: curlimages/curl
  #  depends_on:
  #    - api
  #  command: >-
  #    curl
  #    -X POST
  #    -d "$POST_BODY"
  #    -H "Content-Type: application/json"
  #    http://api:3000/handle)

  curl:
    image: ubuntu
    depends_on:
      - api
    command: >
      bash -c "echo '${POST_BODY}'
      && apt-get update; apt-get install -y curl
      && result=`curl -X POST -d '$POST_BODY' -H 'Content-Type: application/json' http://api:3000/handle`
      && echo '$result'"
