version: "3.9"
services:
  api:
    build: .
    image: simple-api:latest
    ports:
      - "3000:3000"

  curl: 
    image: curlimages/curl
    args:
      - POST_BODY: '{ "name" : "test" }'
    depends_on:
      - api
    command: >-
      curl
      -X POST
      -d ${ POST_BODY }
      -H "Content-Type: application/json"
      http://api:3000/handle
